= LINQ Extension Methods
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

All of the LINQ functionality is exposed as link:extension-methods.adoc[extension methods] off of link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>].
LINQ provides a lot of functionality out of the box and there are many libraries that extend this.
The core extension methods are defined on the https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable[Enumerable] class.

NOTE: To use LINQ import the https://docs.microsoft.com/en-us/dotnet/api/system.linq[System.Linq] namespace.

CAUTION: All the extension methods require that you capture the return value because each method returns the modified list. Data is never changed in place with LINQ.

== Aggregate Methods

Aggregate methods are used to get a single value given a set of values from link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>].

.Aggregate Extension Methods
|===
| Method | Purpose
| 
|===

== Count Related Methods

link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>] is a forward, read only set of items. 
In order to get a count the items have to be enumerated. 
LINQ provides several methods.

.Count Extension Methods
|===
| Method | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.array.empty[Array.Empty<T>] | Gets an empty array.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any[Any] | Determines if there are any items that meet a criteria, if any.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.count[Count] | Gets the number of items.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.empty[Enumerable.Empty<T>] | Gets an empty set of items.
|===

The https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any[Any] method can be used to determine if there are any items in the set or to provide a filter to see if any items match.
It is more efficient than using the https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.count[Count] method since enumeration can stop as soon as an item is found.

.Counting Example
[source,csharp]
----
IEnumerable<Student> students = GetStudents();

int totalStudents = students.Count();

bool hasAtRiskStudents = students.Any(x => x.Grade < 80);
----

The https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.empty[Enumerable.Empty<T>] method is useful for creating an empty link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>].
Like strings and arrays any member returning an link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>] should not return `null`.
Use https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.empty[Enumerable.Empty<T>] instead.

.Empty Example
[source,csharp]
----
public IEnumerable<Student> GetStudents() 
{
   return GetAllCore() ?? Enumerable.Empty<Student>();
}
----

If an empty array is needed then use https://docs.microsoft.com/en-us/dotnet/api/system.array.empty[Array.Empty<T>] instead.
It behaves the same but returns an empty array.

CAUTION: DO NOT create an empty array or list. Use https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.empty[Enumerable.Empty<T>] or https://docs.microsoft.com/en-us/dotnet/api/system.array.empty[Array.Empty<T>] instead.

== Conversion Methods

Sometimes it is necessary to convert something that is enumerable into a more concrete type.
That is what the conversion methods are for.

.Conversion Extension Methods
|===
| Method | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.toarray[ToArray] | Converts an enumerable to an array.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tolist[ToList] | Converts an enumerable to a https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1[List<T>].
|===

The above methods take an link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>] and convert it to the appropriate type.
If the underlying object is already of the appropriate type then nothing happens.

.Conversion Example
[source,csharp]
----
IEnumerable<Student> students = GetStudents();

Student[] studentArray = students.ToArray();
List<Studnent> studentList = students.ToList();
----

The methods require the entire set of items to be enumerated before the method returns.

== Casting Methods

Since https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/[LINQ] requires link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>] an issue comes up when working with older collections that support only https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable[IEnumerable]. 
To convert to link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>] several casting methods are available.

.Cast Extension Methods
|===
| Method | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.cast[Cast<T>] | Converts each value to `T` and throws an exception if it fails.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.oftype[OfType<T>] | Converts each value to `T` and returns those that successfully convert.
|===

NOTE: All these methods use deferred execution.

These methods are primarily used to convert https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable[IEnumerable] instances to link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>].
In both cases the items are enumerated one by one.
In the case of https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.oftype[OfType<T>] the `as` operator is used. If the conversion fails then the item is skipped. 
The https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.cast[Cast<T>] method on the other hand uses a typecast.
If the conversion fails then it throws an exception.

.Cast Example
[source,csharp]
----
//Rows is of type IEnumerable
foreach (var row in table.Rows.OfType<DataRow>())
{
   //row is of type DataRow now
}

//Still safe for Rows but not safe in other cases
foreach (var row in table.Rows.Cast<DataRow>())
{
   //row is of type DataRow now
}
----

== Query Methods

The primary purpose of LINQ is to query data.
For this there are a series of methods available

.Query Extension Methods
|===
| Method | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.groupby[GroupBy<T>] | Groups items by a key. Requires a delegate accepting a `T` and returning the key to use for grouping.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby[OrderBy] | Orders the list of items. Requires a delegate accepting a `T` and returning an expression that can be ordered, generally a property.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select[Select<T>] | Transforms items from one type to another. Requires a delegate accepting a `T` and returning a new type `R`.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.where[Where] | Filters the list of items. Requires a delegate accepting `T` and returning a boolean result.
|===

NOTE: All these methods use deferred execution.

The best way to understand these methods is through an example.

.Query Example
[source,csharp]
----
IEnumerable<Student> students = GetStudents();

//Get students who are at risk of failing
//Order by student last name and then first name
//Then transform to a summary object for the UI
var atRiskStudents = students.Where(x => x.Grade >= 70 && x.Grade < 80)
                             .OrderBy(x => x.LastName).Thenby(x => x.FirstName)
                             .Select(x => new StudentSummary(x.FirstName, x.LastName, "At Risk"));
----

NOTE: Chaining the methods together is common.

Use https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.where[Where] to filter the items to a subset.
Any number of calls can be combined together as needed.
Use https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select[Select<T>] to convert a set of items to another type. 
This is most useful for getting a subset of the data.

The https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby[OrderBy] orders the items, generally by a property.
To order descending use https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderbydescending[OrderByDescending].
For additional ordering use https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.thenby[ThenBy] or https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.thenbydescending[ThenByDescending] otherwise the ordering will not be combined properly.

== Join Methods

In some cases it is necessary to add or remove items from a set of items.
There are extension methods for that.

.Join Extension Methods
|===
| Method | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except[Except] | Returns items except those matching the given set of items.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.union[Union] | Returns the union of two sets of items.
|===

The biggest issue with these methods is that they use equality comparison. 
To use a different comparison provide an implementation of https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1[IEqualityComparer<T>].

.Joining Example
[source,csharp]
----
IEnumerable<Assignment> assignments = GetAssignments()
                                          .Union(GetExams())
                                          .Union(GetExtraCredit());
----

== Singular Methods

Sometimes it is necessary to get a single item.
In many cases https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.where[Where] has been used to filter down to the desired item but the results are still link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>].

.Singular Extension Methods
|===
| Method | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.first[First] | Returns the first item or throws an exception if there are none.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.firstordefault[FirstOrDefault] | Returns the first item, if any.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.last[Last] | Returns the last item or throws an exception if there are none.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.lastordefault[LastOrDefault] | Returns the last item, if any.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single[Single] | Returns the only item or throws an exception if there are none or more than one.
| https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.singleordefault[SingleOrDefault] | Returns the only item, if any, or throws an exception if there are more than one.
|===

All the methods return back a single item.
They only vary in where they get the item from and how they handle missing items.

.Getting a Student
[source,csharp]
----
public Student GetStudent ( int id )
{
   return _students.Where(x => x.Id == id)
                   .FirstOrDefault();
}

private readonly List<Student> _students = new List<Student>();
----

It is very common to first filter the list of items and then select the only remaining item.
There are overloads on these methods to accept the filtering criteria just like with the https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.where[Where] method.

.Getting a Student
[source,csharp]
----
public Student GetStudent ( int id )
{
   return _students.FirstOrDefault(x => x.Id == id);
}

private readonly List<Student> _students = new List<Student>();
----

CAUTION: Prefer to use https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.firstordefault[FirstOrDefault] whenever possible. It is the most efficient method and works in all cases. The other methods may not behave correctly with all providers.

== See Also

link:readme.adoc[Advanced Types] +
link:extensionmethods.adoc[Extension Methods] +
link:linq.adoc[LINQ] +
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable[.NET Enumerable Class] +
