= LINQ
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/[LINQ], Language Integrated Natural Query, is a framework for writing natural queries against enumerable sets of items in .NET. Earlier link:extension-methods.adoc[extension methods] were introduced as a way to extend types that otherwise could not be extended with new "instance" methods.
Extension methods provide the illusion of being an instance method when in reality they are static methods on a link:static-classes.adoc[static class].

== Extension Methods

LINQ provides its functionality as extenion methods off the link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>] interface.
LINQ only works with link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>].

Refer to the section link:linq-extension-methods.adoc[LINQ Extension Methods] for a discussion on some of the more commonly used extension methods.

== LINQ Syntax

While the extension methods are useful they are not exactly natural. 
In C# there is a more natural way of writing some LINQ queries.

Refer to the section link:linq-syntax.adoc[LINQ Syntax] for more information on the LINQ syntax.

== LINQ Providers

In order to work properly LINQ requires providers.
A provider implements the core behavior of LINQ.
In-memory data structures are implemented by the framework but other structures require a provider.
In most cases it is not necessary to pay attention to the provider being used because it cannot be changed anyway.

However an important impact of the provider is that it may not implement all the functionality of LINQ.
The only way to known whether a provider implements the necessary functionality is to actually use it.
Therefore be sure to always test code against the provider that is needed as it may behave differently than the in-memory version.

== See Also

link:readme.adoc[Advanced Types] +
link:deferred-execution.adoc[Deferred Execution] +
link:linq-extension-methods.adoc[LINQ Extension Methods] +
link:linq-syntax.adoc[LINQ Syntax] +
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/[.NET LINQ] +