= Exceptions
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

An exception is an error that occurs in a program. In most cases an exception is an "exception" to the normal flow of the code. When an error occurs the runtime captures information about the error into an object, the exception. For more information on how to report an error refer to link:throwing-exceptions.adoc[Throwing Exceptions]. 

Raising, or throwing, an exception, is important so that calling code can potentially recover from an error, such as a missing file. Refer to the section link:handling-exceptions.adoc[Handling Exceptions] for more information on how to handle errors.

== Why

The first question that tends to come up when moving from a language that does not support exceptions is why? In languages likes C++ (that do support exceptions) it is common to use the return type of a function to indicate success or failure. The problem with this approach is that it is opt-in. Calling code must:

- Know to check the return value of the function.
- Explicitly check the return value.
- Verify they are correctly interpreting the results.

While opt-in error handling may be useful in some cases (e.g. try methods) most of the time errors are errors and code should be forced to handle them. That is why exceptions are preferred. Relying on calling code to check for errors is about as useful as simply ignoring errors altogether. 

== Exception Class

The base type of all errors is https://docs.microsoft.com/en-us/dotnet/api/system.exception[Exception] in .NET. This type provides useful information about the error that occurred.

.Exception Class Members
|===
| Property | Type | Description
| https://docs.microsoft.com/en-us/dotnet/api/system.exception.message[Message] | `string` | Error message
| https://docs.microsoft.com/en-us/dotnet/api/system.exception.innerexception[InnerException] | `Exception` | Nested error, if any
| https://docs.microsoft.com/en-us/dotnet/api/system.exception.stacktrace[StackTrace] | `string` | Call stack at point of exception
|===

== Common Exceptions

The https://docs.microsoft.com/en-us/dotnet/api/system.exception[Exception] class only provides basic information about an error. Unless code parses the https://docs.microsoft.com/en-us/dotnet/api/system.exception.message[Message] property it is difficult to determine how to handle the error. Derived types can be used to provide more information about what went wrong. More importantly the exception type allows code handle different types of errors differently.

There are many different exception types in .NET (all deriving from https://docs.microsoft.com/en-us/dotnet/api/system.exception[System.Exception]) to support some of the most common error cases. When reporting errors it is important to use the most appropriate exception type so that calling code can better handle the error.

=== Argument Exceptions

Errors related to arguments in a method are probably the most common. .NET provides the base class https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception[ArgumentException] to represent errors related to arguments. This general purpose exception should be used when reporting errors related to arguments.

https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception[ArgumentException] adds a single new property to the eror information, https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception.paramname[ParamName]. This property provides information about what argument was invalid. This property is useful when a method accepts multiple arguments since it can be used to identify which of the arguments is invalid. 

There are several derived types that should be used for more-specific errors. If there is not a better derived type then use the base https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception[ArgumentException] instead.

.Types of Argument Exceptions
|===
| Type | Usage
| https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception[ArgumentNullException] | An argument is `null` and it was not expected.
| https://docs.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception[ArgumentOutOfRangeException] | An argument (generally a numeric value) is out of the expected range.
|===

=== Invalid Operations

In some cases a request may not be valid now but might work later. An example might be withdrawing money from a bank. If there are insufficent funds or the bank is undergoing maintenance then withdrawals may fail. But this does not mean all withdrawals will fail but rather the error is temporary. Trying again later, potentially after the account has been updated, may succeed. 

The https://docs.microsoft.com/en-us/dotnet/api/system.invalidoperationexception[InvalidOperationException] is used to report when a request is not valid, but might be in the future. In most cases the request itself is valid, and therefore does not require correction, but it just cannot be done right now. Calling code may opt to try the request later or abort the request altogether depending upon what was requested.

=== Validation Exceptions

The https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.ivalidatableobject[IValidatableObject] interface is used to validate instances. Because validation is important to .NET a dedicated exception, https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validationexception[ValidationException], is provided for it. You normally do not raise this exception yourself but instead rely on https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validator.validateobject[Validator.ValidateObject] to raise the exception for you.

This exception is useful when reporting errors to the user. Validation errors are almost always the result of bad user input and therefore are expected. By using `ValidationException` calling code can determine data is invalid and report it back to the user to correct. The https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validationexception.validationresult[ValidationResult] property indicates what validation rule failed. Calling code can use this to get the underlying validation message and report it back to the user, if desired.

== Application Exceptions

Applications can create their own custom exceptions, deriving from https://docs.microsoft.com/en-us/dotnet/api/system.exception[Exception], if desired. This should be a rare case. The only time creating a custom exception would be useful is if an application needs to distinguish errors for custom scenarios within the application.

Creating custom exceptions is beyond the scope of this topic. It requires understanding how serialization works and correctly defining the exception type. Refer to the online documentation if you need more information.

NOTE: There is an `ApplicationException` class in .NET that was originally designed to be the base class for all application exceptions. Starting in .NET 2.0 this type has been deprecated. Do not use it in your code. 

== System Exceptions

There is a special class of exceptions known as system exceptions. System exceptions are reserved by the framework to be raised only by it. While there is nothing preventing you from raising these exceptions yourself they are really designed for exclusive use by the framework. All system exceptions derive from https://docs.microsoft.com/en-us/dotnet/api/system.systemexception[SystemException].

While you will never raise these exceptions yourself you may want to handle some. Here are some more common system exceptions.

.Common System Exceptions
|===
| Type | Fatal | Used When
| https://docs.microsoft.com/en-us/dotnet/api/system.nullreferenceexception[NullReferenceException] | No | Thrown when attempting to access an instance member on a `null` object.
| https://docs.microsoft.com/en-us/dotnet/api/system.outofmemoryexception[OutOfMemoryException] | Yes | Thrown when the application runs out of memory.
| https://docs.microsoft.com/en-us/dotnet/api/system.stackoverflowexception[StackOverflowException] | Yes | Thrown when the stack overflows or is corrupted.
|===

Fatal exceptions can be handled but will most likely fail when being handled. In all cases fatal exceptions will cause the process to terminate irrelevant of any error handling. They are unrecoverable.

WARNING: Never throw a system exception in your code.

== See Also

link:readme.adoc[Error Handling] +
link:handling-exceptions.adoc[Handling Exceptions] +
link:raising-exceptions.adoc[Raising Exceptions] +
https://docs.microsoft.com/en-us/dotnet/api/system.exception[Exception Class] +