= Try-Catch Statement
v1.0
:toc:

The https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch[try-catch] statement in C# is used to handle an exception that has occurred in code.
To handle errors wrap the code that may fail in a https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch[try-catch] statement.

NOTE: Refer to link:throwing-exceptions.adoc[Throwing Exceptions] for information on how to throw an exception.

The https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch[try-catch] statement has the following syntax.

.Try-Catch Syntax
----
try-catch-statement ::= try-block catch-conditional-block* [catch-block] ;
try-block ::= try S
catch-conditional-block ::= catch ( T id ) S
catch-block ::= catch S
catch-expression ::= ( T id )
----

== Simple Form

The simplest https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch[try-catch] statement consists of the `try` and `catch` blocks.
This is also known as a "catch all" because all exceptions are handled.

.Simple Try-Catch Example
[source,csharp]
----
try
{
   //Statements to try to execute
} catch 
{
   //Statements to handle exceptions
}
----

The statements inside the `try` block are executed.
If any exception is thrown then the block immediately stops executing and control transitions to the `catch` block.
The statements inside the `catch` block are executed.
Execution then resumes after the `try-catch` statement.

CAUTION: If an exception occurs no additional statements after the line causing the exception will execute inside the `try` block.

If no exception is thrown by the end of the `try` block then execution resumes after the `catch` block.
The statements inside the `catch` block are not executed.

NOTE: This form of the `try-catch` should rarely be used.

== Typed Try Catch

The more common form of the https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch[try-catch] statement specifies the type of exception to handle.

.Typed Try-Catch Example
[source,csharp]
----
try
{
   //Statements to try to execute
} catch (FileNotFoundException e)
{
   //Statements to handle "file not found" exception
}
----

In this form the `catch` block specifies the type of exception to handle.
If an exception occurs and the exception is type compatible with the given type then the `catch` block is executed.
If the exception does not match the type specified then the `catch` block is ignored.

This is the most appropriate form of https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch[try-catch] because code should only handle exceptions that they can recover from. 
The only way to know what exceptions are recoverable is to use the exception type.

Multiple typed catch blocks are allowed allowing for handling different exceptions in different ways.

.Multiple Typed Try-Catch Example
[source,csharp]
----
try
{
   //Statements to try to execute
} catch (FileNotFoundException e)
{
   //Statements to handle "file not found" exception
} catch (IOException e)
{
   //General IO error
}
----

When multiple catch blocks are present then the runtime works from top to bottom until it finds a compatible exception type.
Only a single catch block will run.

== Catch All Blocks

The final `catch` block of `try-catch` can be untyped.
This block is executed if no other `catch` block is executed and is most useful when logging unhandled exceptions before terminating the application.

There are two different formats for this `catch` block.
The less useful form is the original syntax shown.
The more useful form uses https://docs.microsoft.com/en-us/dotnet/api/system.exception[Exception] as the exception type. 
This gives the block access to the exception information.

.Catch All Block
[source,csharp]
----
try
{
   //Do something
} catch (Exception e)  //Catch all with access to the exception information
{
} catch //Catch all but no access to the exception information
{   
};
----

NOTE: Do not use both forms in the same `try-catch`. One is sufficient.

== Exception Filters

C# also supports exception filters which allow for a function to filter exceptions.
That is beyond the scope of this course.

== See Also

link:readme.adoc[Error Handling] +
link:handling-exceptions.adoc[Handling Exceptions] +
link:try-finally.adoc[Try Finally Statement] +
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch[C# Try-Catch Statement] +
