= File Class
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

Many programs need to read and write files. .NET has support for files (and directories) but its approach is a little different from most other languages. .NET breaks up file operations into several different classes depending upon what you want to do.

== File Management

To manage files use the https://docs.microsoft.com/en-us/dotnet/api/system.io.file[File] class.
It is a static class containing helper functions for working with files. This can include copying, renaming or deleting files.

NOTE: The classes related to IO are in the https://docs.microsoft.com/en-us/dotnet/api/system.io[System.IO] namespace.

==  Common File Operations

=== Determine If a File Exists

Use the https://docs.microsoft.com/en-us/dotnet/api/system.io.file.exists[File.Exists] method to determine if a file exists.

.Determining if a file exists
[source,csharp]
----
var filename = "Somefile.txt";
if (File.Exists(filename))
   ; //File exists
----

Most file operations will fail if a file does not exist.
Use this method to check before attempting a file operation.

CAUTION: Even when using this method it is possible for a file to be removed before the file operation occurs. Therefore you should always use error handling to recover from a missing file.

=== Copy a File

Use the https://docs.microsoft.com/en-us/dotnet/api/system.io.file.copy[File.Copy] method to copy a file from one location to another.

.Copying a File
[source,csharp]
----
var sourceFile = "SomeFile.txt";
var targetFile = "NewFile.txt";

File.Copy(sourceFile, targetFile);
----

If the target file already exists then the method fails. To overwrite an existing file use the overload accepting a `bool` or delete the file first.

=== Delete a File

Use the https://docs.microsoft.com/en-us/dotnet/api/system.io.file.delete[File.Delete] method to delete a file.

.Deleting a File
[source,csharp]
----
var filename = "SomeFile.txt";

File.Delete(filename);
----

If the file is read only or locked then the method fails.

=== Move a File

Use the https://docs.microsoft.com/en-us/dotnet/api/system.io.file.move[File.Move] method to move or rename a file.

.Moving a File
[source,csharp]
----
var sourceFile = "SomeFile.txt";
var targetFile = "NewFile.txt";

File.Move(sourceFile, targetFile);
----

If the file already exists it will fail. Delete the file first.

If you move a file across volumes (e.g. `C:\` to `D:\`) then it will normally work.
If the source file is locked the file is copied instead.

== File Exceptions

For most file operations the call will fail if the file name is `null`, empty or an invalid path. In addition to the standard exceptions, the following exceptions are also commonly raised by file operations.

.Common File Exceptions
|===
| Exception | Description
| https://docs.microsoft.com/en-us/dotnet/api/system.io.directorynotfoundexception[DirectoryNotFoundException] | The filename contains a directory path that could not be found.
| https://docs.microsoft.com/en-us/dotnet/api/system.io.filenotfoundexception[FileNotFoundException] | The file could not be found.
| https://docs.microsoft.com/en-us/dotnet/api/system.io.pathtoolongexception[PathTooLongException] | The path exceeds the size allowed by the file system.
| https://docs.microsoft.com/en-us/dotnet/api/system.unauthorizedaccessexception[UnauthorizedAccessException] | The user does not have permission to access the file or directory.
| https://docs.microsoft.com/en-us/dotnet/api/system.io.ioexception[IOException] | An error occurred trying to perform the operation. This is the base class for most of the other exceptions so list it last when using link:../error-handling/handling-exceptions.md)[try-catch] blocks.
|===

== Reading and Writing Files

When reading or writing a file a choice must be made on how to read the file.

Buffered::
   The entire file, or a significant subset, is read into memory and processed.
Streamed::
   The file data is streamed into memory such that only a subset of the file is in memory at any one time.

There are plusses and minuses to both approaches.
Refer to the section link:buffered-io.adoc[Buffered IO] for more information on buffered IO and link:stream-io.adoc[Stream IO] for more information on streaming.

=== Text and Binary Files

When working with the contents of a file pay particular attention to whether it is a text or binary file.
The framework does not attempt to translate binary files in any way.
Binary files are simply streams of bytes.

Text files are treated as chacters, of a variety of encoding schemes, and converted to strings.
When working with a text file the file encoding must be specified.
Selecting the wrong encoding can result in corrupt characters being read or written.
By default the framework will attempt to figure out the encoding based upon the file contents.
In reality if the file contains a Unicode marker at the beginning of the file then it is read as Unicode otherwise it is treated as Ansi.

Refer to https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding[Encoding] in the .NET documentation for more information on encoding.

== File Paths

The https://docs.microsoft.com/en-us/dotnet/api/system.io.file[File] class does not manage paths.
It simply passes any file paths onto the file system.
To work with file paths refer to the link:paths.adoc[Paths] section.

== See Also

link:readme.adoc[File IO] +
link:paths.adoc[Paths] +
link:stream-io.adoc[Stream IO] +
https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter[.NET BitConverter Class] +
https://docs.microsoft.com/en-us/dotnet/api/system.io.directory[.NET Directory Class] +
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding[.NET Encoding] +
https://docs.microsoft.com/en-us/dotnet/api/system.io.file[.NET File Class] +
https://docs.microsoft.com/en-us/dotnet/api/system.io.stream[.NET Stream Class] +
