= Calling Functions
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

Function calls are one of the most common types of expressions. The syntax for calling a function is given below.

.Function Call Syntax
----
function-call => func ( [argument-list] )
argument-list => argument { , argument }*
argument => E
----

A function call consists of the function name with a set of parenthesis. Inside the parenthesis is zero or more arguments. The function parameters determine how many arguments are required.

NOTE: `void` is not valid in an argument list.

For each argument any expression can be used (including other function calls) provided the expression is type compatible with the parameter. Arguments must appear in the same order as the parameters.

If the compiler cannot unique match a function call to the exact function definition then it is a compiler error.

.Calling a Function
[source,csharp]
----
//Call a function to print 2 integers
Print(10, 20);

//Call a function to print 3 doubles
PrintDouble(10, 12.5, 20);
----

== Function Expressions

If a function returns a value then it can be used as an expression instead. 

.Calling a Function in an Expression
[sorce,csharp]
----
//Call a function to calculate area
double area = CalculateArea(10, 20);

//Call a function to calculate volume and add and adjustment
double volume = CalculateVolume(10, 12.5, 20) + 50;
----

NOTE: When calling a function as part of an expression leave the semicolon off the function call.

When calling a function in an expression the type of the expression is the return type of the function.

== Optional Arguments

== See Also

link:expressions.adoc[Expressions] +
