= Control Flow Statements
Michael Taylor <michael.taylor@tccd.edu>
v1.1
:toc:

C# has all the standard control flow statements.
A control flow statement alters the typical top to the bottom flow of code.
Control flow statements are generally broken up into decision and looping statements.

NOTE: Unless otherwise stated all the control flow statements all a single statement to run. To run more than one statement use the block statement.

Decision statements, sometimes called conditional staetments, allow code to be executed depending upon some condition. 
In C# there are two decision statements: link:if-statement.adoc[if] and the more complex link:switch-statement.adoc[switch].

Looping statements keep executing the same set of statements until some condition is met. C# has the link:while-statement.adoc[while], link:do-statement.adoc[do while], 
link:for-statement.adoc[for] and `foreach` statements.

NOTE: The `foreach` statement is used when working with lists of items and will be discussed later.

When discussing looping statements the term `loop variant` will be used.

Loop Variant::
   A variable whose values is changed by the loop (such as a counter or a condition).

In addition to the decision and looping statements the link:break-statement[break] and link:continue-statement.adoc[continue] statements are used in the looping statements.
 
== See Also

link:break-statement.adoc[Break Statement] +
link:continue-statement.adoc[Continue Statement] +
link:do-statement.adoc[Do While Statement] +
link:for-statement.adoc[For Statement] +
link:if-statement.adoc[If Statement] +
link:switch-statement.adoc[Switch Statement] +
link:while-statement.adoc[While Statement] +
