= Identifiers
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

An identifier in C#, like almost all programming languages, is a user defined symbol that has some meaning. Identifiers are used to identify variables, function, types and other user-provided values. 

NOTE: In Visual Studio you can right click an identifiers and select `Goto Definition` (default key is `F12`) to quickly jump to the definition of the identifier.

== Identifier Rules

Before an identifier can be used it must be defined. Later sections will talk about how to define identifiers but in all cases some rules apply. The following rules must be followed when defining an identifier.

* An identifier must start with a letter or underscore.
* An identifier must consist of letters, digits and underscores.
* An identifier cannot be a keyword.
* An identifier must be unique within its scope. When crossing scopes some rules apply that will be discussed later.

CAUTION: If the IDE or compiler generates an error about an identifier being undefined then verify the: spelling, case and scope to ensure they are all correct.

== Casing Styles

There are several different styles of casing in programming.

Camel Casing::
   Camel casing capitalizes on word boundaries except the first word. Camel casing does not use underscores. Examples include `payRate`, `firstName` and `rateOfPay`.
Pascal Casing::
   Pascal casing capitalizes on word boundaries including the first word. Pascal casing does not use underscores. Examples include `Program`, `MyData` and `DateTime`.
Snake Casing::
   Snake casing is camel casing but instead of capitalizing on word boundaries a dash is used as for a space yet. This casing is not used in C#. Eaxmples include `pay-rate`, `first-name` and `date-time`.

In C# the following guidelines apply to casing. More guidelines will be given later.

* DO USE lower case for keywords.
* DO USE the correct casing for identifiers based upon the standard styling rules of C#.
* DO NOT USE casing to differentiate identifiers in the same scope.

One difference between C# and most other languages is that C# is context sensitive. That means that some identifiers are keywords in some contexts but keywords in others.

CAUTION: It is possible to use keywords as identifiers if prepended with an at (`@`) sign. This is only needed when the identifier is a keyword in the given context. However this is never a good idea and should not be used in code. 

Another difference between C# and other C-based languages is that C# follows different scoping rules even on the same line. Therefore it is possible to use the same identifier but with different means. The rules for this will be discussed later.

== Naming Guidelines

Good identifiers explain the purpose of something and should be understand based solely on the name. Even with an IDE like Visual Studio it is still important to be able to quickly find identifiers so use descriptive words and avoid slang, acronyms and abbreviations. The following guidelines apply for naming identifiers.

* DO USE simple words with camel or Pascal casing, depending on context.
* DO USE descriptive identifiers so the meaning is clear.
* DO limit the length of the identifier to the minimal needed to clearly identify the purpose.
* DO leave out connector words like `the`, `of` and `for`.
* DO NOT USE https://en.wikipedia.org/wiki/Hungarian_notation[Hungarian notation].
* DO NOT USE abbreviations or acronyms in identifiers unless it is well known.
* DO NOT USE keywords as identifiers except when the keyword is context sensitive.

The exception is for well known abbreviations or acronyms that would be understood by anyone reading the code.

[source,csharp]
----
//Good identifiers
payRate
firstName
okButton

//Bad identifiers
temp    
x       
nbrStudents
student1
----