= Datasets
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

The https://docs.microsoft.com/en-us/dotnet/api/system.data.dataset[Dataset] is an in-memory representation of a database.
Since it is unrealistic to store the entire database in memory the dataset only contains the set of tables, columns and rows needed for the request. Specifically the dataset is populated with the table(s), columns and rows from the query that is used to populate it.

== Data Adapters

Before getting into using a dataset it is necessary to talk about a https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdataadapter[data adapter].
Data adapters adapt data to and from the database.
Ultimately a data adapter is simply a wrapper around the commands that need to be run to get data into and out of a database.
Remember that a dataset is an in-memory representation of tables.
Therefore it can be used to modify the tables and send them back to the database.
To update data in the database ultimately requires an: insert, update or delete command depending upon the change.
To retrieve data you need a select command.
Since a dataset can do all this it needs all the commands in order to retrieve and set data.
That is where the data adapter comes in.

The data adapter contains the following core properties.

.Data Adapter Properties
|===
| Property | Description
| https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldataadapter.deletecommand[DeleteCommand] | Deletes rows from a table.
| https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldataadapter.insertcommand[InsertCommand] | Inserts rows into the table.
| https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldataadapter.updatecommand[UpdateCommand] | Updates rows in the table.
| https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldataadapter.selectcommand[SelectCommand] | Reads data from the table.
|===

If the table is only being read then the https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldataadapter.selectcommand[SelectCommand] needs to be set otherwise all the commands need to be set.
Each command contains the SQL code to execute and the connection to use. 

Refer to the section on modifying data for more information.

CAUTION: While each command has its own connection object and could technically point to a different database this would ultimately cause the update to fail.

== Populating a Dataset

To populate a dataset do the following.

1. Create the dataset.
1. Create the select command.
1. Create the data adapter.
1. Set the https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldataadapter.selectcommand[SelectCommand] property on the data adapter.
1. Call the https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdataadapter.fill[Fill] method on the data adapter passing the dataset to it.

.Populating a Dataset
[source,csharp]
----
var command = conn.CreateCommand();
command.CommandText = "SELECT ...";

var da = new SqlDataAdapter() {
   SelectCommand = command
};

var ds = new Dataset();

da.Fill(ds);
----

Once the method returns the dataset contains the data from the select command.

== Enumerating Rows

A dataset can contain multiple tables (or none) but generally a query returns one table.
Unfortunately ADO.NET was written before generics and none of the existing types were updated to support the link:../chapter-6/interface-ienumerable.adoc[IEnumerable<T>] interface and therefore LINQ does not work.
However the https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.oftype[OfType] method from LINQ can convert an `IEnumerable` to `IEnumerable<T>` safely.

.Convering IEnumerable to IEnumerable<T>
[source,csharp]
----
IEnuemrable<DataTable> tables = ds.Tables.OfType<DataTable>();
----

Once converted to an `IEnumerable<T>` LINQ is now available.
To get the first table from the dataset use the https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.firstordefault[FirstOrDefault] method.

.Get the First Table
[source,csharp]
----
var table = ds.Tables.OfType<DataTable>.FirstOrDefault();
if (table != null)
{ 
   ...
};
----

CAUTION: The table name is not defined. It is generally a generic name like `Table1` or `Table`.

To enumerate the rows of a table use a similar approach of casting the `IEnumerable` https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.rows[Rows] property to `IEnumerable<DataRow>`.

.Enumerating Rows of a Table
[source,csharp]
----
foreach (var row in table.Rows.OfType<DataRow>())
{
   ...
};
----

== Reading Data

Reading data from a row can be done in several different ways.

NOTE: Refer to the section link:reading-data.adoc[Reading Data] for information on using ordinals vs strings when reading data.

=== Field Method

The https://docs.microsoft.com/en-us/dotnet/api/system.data.datarowextensions.field[Field<T>] method can be used.
This is an extension method that adds generic support to retrieving data.

.Reading using Field
[source,csharp]
----
var id = row.Field<int>(0);
var name = row.Field<string>("Name");
----

The method can be used with either a zero-based ordinal or a column name.
While the method is generic, attempting to use anything beyond a primitive, string or byte array will generally result in an exception.

=== Array Syntax

Yet another approach is to use array syntax on the reader.

.Reading using Array Syntax
[source,csharp]
----
var idValue = row[0];

//Convert to int
var id = Convert.ToInt32(idValue);

var name = row["Name"]?.ToString();
----

Once again either a zero-based ordinal or column name can be used to identify the column.

The advantage of this approach is that value is returned as an `object` which makes it easier to handle unknown data.
Calling code must convert to a more specific type if needed. 

== Detecting Null

Use the https://docs.microsoft.com/en-us/dotnet/api/system.data.datarow.isnull[IsNull] method to check for a database null.

.Using IsNUll
[source,csharp]
----
var description = row.IsNull(0) ? "" : row.Field<string>(0);
var rating = row.IsNull("Rating") ? "" : row.Field<string>("Rating");
----

Refer to link:reading-data.adoc[Reading Data] for more information on database nulls.

== Making Changes to the Data

To modify data using a dataset first load the data using the https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdataadapter.fill[Fill] method.
Then make changes to the data in the dataset.
This can include adding new rows, modifying existing data or deleting rows. 

Under the hood the https://docs.microsoft.com/en-us/dotnet/api/system.data.dataset[DataSet] is tracking modifications to rows and the addition and deletion of rows.

=== Adding Rows

To add a row to a datatable there are a couple of approaches.
The first approach is to create the https://docs.microsoft.com/en-us/dotnet/api/system.data.datarow[DataRow] instance, populate the columns and then add the row.
Because a row require a specific set of columns it has to be created using the https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.newrow[DataTable.NewRow] method.
This method only creates the row, it does not add it.

.Adding a Row
[source,csharp]
----
var row = table.NewRow();
row["Name"] = "Jaws";
row["Description"] = "Shark movie";
row["Rating"] = "PG";

table.Rows.Add(row);
----

https://docs.microsoft.com/en-us/dotnet/api/system.data.datarow[DataRow] allows either ordinal or column names to be used.

CAUTION: Ensure that the row is added to the datatable using the https://docs.microsoft.com/en-us/dotnet/api/system.data.datarowcollection.Add[Add] method of the https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.rows[DataTable.Rows] property. Creating a new row does not add it to the table.

=== Modifying Rows

To modify an existing row find it in the table and then use the array syntax to modify the column values using either ordinal or column names.

.Modifying a Row
[source,csharp]
----
var row = table.Rows.Find(10);

row["Description"] = "First movie";
----

=== Deleting Rows

To delete a row use the https://docs.microsoft.com/en-us/dotnet/api/system.data.datarowcollection.remove[Remove] method of the https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.rows[DataTable.Rows] property.

.Deleting a Row
[source,csharp]
----
var row = table.Rows.Find(10);

table.Rows.Remove(row);
----

=== Saving Changes

Once the rows have been modified use the https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdataadapter.update[Update] method on the data adapter to push the changes back to the database.

.Configuring a Data Adapter
[source,csharp]
----
var insertCommand = conn.CreateCommand();
insertCommand.CommandText = "INSERT INTO ...";

var deleteCommand = conn.CreateCommand();
deleteCommand.CommandText = "DELETE FROM ...";

var updateCommand = conn.CreateCommand();
updateCommand.CommandText = "UPDATE ...";

var selectCommand = conn.CreateCommand();
selectCommand.CommandText = "SELECT ...";

var da = new SqlDataAdapter() {
   InsertCommand = insertCommand,
   DeleteCommand = deleteCommand,
   UpdateCommand = updateCommand
};

//Load the data
var ds = new Dataset();
da.Fill(ds);

//Modify the data
//...

//Save the data
da.Update(ds);
----

The dataset tracks the original values loaded and any changes made.
When https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdataadapter.update[Update] is called it enumerates all the changes and applies them to the database.
This is all done in a batch so either all changes are made or they all fail.

== Creating an In Memory Database

Since a dataset represents an in-memory database it can be used to build a database structure in code for such things as testing or for seeding a database.
To build an in-memory database code must define the table(s) in the database and the columns for each table.
Optionally the code can add rows for each table.

=== Creating a Table

To create a table create an instance of https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable[DataTable] and set the columns.
Tables should generally be given descriptive names but this is only necessary if persisting data.
Once the table is created add it to the https://docs.microsoft.com/en-us/dotnet/api/system.data.dataset.tables[Dataset.Tables] property.

.Creating a Table
[source,csharp]
----
var table = new DataTable("Products");

//Add columns
//Optionally add rows

//Add to parent dataset
dsParent.Tables.Add(table);
----

The order in which tables are added does not matter however if relationships need to be set up it is generally better to add tables in order.

=== Creating a Column

To create a simple column in a table use the https://docs.microsoft.com/en-us/dotnet/api/system.data.datacolumncollection.add[Add] method of the https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.columns[DataTable.Columns] property.
It requires just the column name and type.

.Adding a Simple Column
[source,csharp]
----
var colName = table.Columns.Add("Name", typeof(string));
----

Alternatively create the https://docs.microsoft.com/en-us/dotnet/api/system.data.datacolumn[DataColumn] instance explicitly with the appropriate name, type and constraints and use the overload of https://docs.microsoft.com/en-us/dotnet/api/system.data.datacolumncollection.add[Add] that accepts the column instance.

.Adding a Complex Column
[source,csharp]
----
var colId = new DataColumn("Id", typeof(int))
colId.AllowDBNull = false;
colId.AutoIncrement = true;

table.Columns.Add(colId);
----

=== Adding Rows

Adding rows to an in-memory dataset works just like a dataset obtained from a database.
You can use the https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.rows[DataTable.Rows] property to add rows.

.Adding Rows to a Table
[source,csharp]
----
var row = table.NewRow();
row["Id"] = 1;
row["Name"] = "Bob";
table.Rows.Add(row);
----

== Advantages and Disadvantages of Datasets

The primary benefit of datasets is the ability to quickly load data from a database and be able to manipulate the data without adding too much extra code.

Datasets have some pros and cons that you should consider before using them.

You may want to use a dataset if any of the following apply.

- The data needs to be modified and pushed back to the database.
- You need to load and work with table relationships.
- You do not have a .NET type that represents the data being returned by the query.
- The amount of data being returned is small (e.g. less than a couple hundred rows).
- You are on an unstable network (e.g. mobile applications) and need a disconnected copy of the data.
- The structure of the data is not known in advance (e.g. dynamic queries).

You should consider using a data reader or other approach if any of the following apply.

- Performance is critical. Datasets use data readers under the hood to read data and must build the table structure which is slow.
- Memory constraints are tight. Datasets keep a copy of the schema plus at least one copy of each row. 
- The amount of data is large (e.g. more than a couple hundred of rows). The overhead of a dataset gets worse as the number of rows increase.
- You are going to convert the rows of data to a business object.
- You need read only access to the data.

== See Also

link:readme.adoc[Data Access] +
link:datareader.adoc[Data Readers] +
link:reading-data.adoc[Reading Data] +
https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdataadapter[.NET Data Adapters] +
https://docs.microsoft.com/en-us/dotnet/api/system.data.datarow[.NET DataRow Class] +
https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable[.NET DataTable Class] +

