= Building a Data Access Layer
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

In a typical application architecture it is important to separate the layers of an application into different components. Modularizing an application provides many benefits including:

- Change or replace modules without breaking other modules.
- Distributing work to different people provided they are not working on the same modules.
- Providing a cleaner break in responsibility to help ensure no one piece of code is doing too much.

In a typical 3-layer application the layers include: presentation, business and data. Most of the time the layers are separate assemblies but this is not technically required. In a pure architecture each layer may only talk to layers lower than it. For example the presentation layer can talk to the business layer but not the data layer.

== Presentation

The presentation layer is the UI of the application. The presentation layer is responsible for displaying information to the user and reacting to user requests. 

Often the UI needs information in particular formats and the presentation layer is responsible for converting to/from business objects to presentation-friendly objects. The presentation may also need to translate user requests to the appropriate call to business functionality.

For applications supporting multple platforms there may be multiple presentation layers. For example there may be a Windows application layer for native Windows applications, a separate web layer for a web application and yet another layer for a mobile application.

The presentation layer may only communicate with the business layer.

== Business

The buinsess layer is responsible for the bulk of the application logic. Business rules such as required fields, interaction between components and data constraints are enforced here. Business layers can be architected in any number of ways.

The primary goal of the business layer is to enforce business rules. The business layer has no understanding of how data may be rendered in a UI so it normally provides data in business-friendly objects. The business layer is also not responsible for persistence, if any, of data so it ignores that aspect.

The business layer may only communicate with the data layer.

== Data

The data layer is responsible for loading and saving data. Whether this data comes from a traditional database, file system or even a server on another machine is not relevant. 

The data layer normally works with objects that are persistence friendly. For databases this is likely the table structures. Data layers are generally sensitive to changes in the persistence layer but ideally do not bubble any of these concerns up to the business layer.

The data layer is only responsible for data consistency. Business rules and relationships are enforced in the higher business layer. The data layer may implement cross cuttin concerns like caching for performance reasons.

== See Also

link:readme.adoc[Data Access] +
https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures[Common Web Application Architectures] +
https://en.wikipedia.org/wiki/Multitier_architecture[Multitier Architecture] +
https://www.codeproject.com/Articles/36847/Three-Layer-Architecture-in-C-NET-2[Three Layer Architecture in C#] +
https://stackify.com/n-tier-architecture/[What is N-Tier Architecture] +
