= Documentation
Michael Taylor <michael.taylor@tccd.edu>
v0.1
:toc:

Especially when creating publicly consummable types it is important to document the class purpose and any information related to using the type. Anyone using the code will generally not have access to the source code but they do have access to the documentation, provided it follows the documentation guidelines (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments[doctags]) used by C#. The IDE is configured to read the documentation and provide portions of it to calling code.


The general syntax of a doctag is three slashes before the declaration being documented. The IDE will generally auto-populate the doctags needed based upon the declaration.

.Simple Doctag
[source,csharp]
----
/// <summary>Represents a rectangle.</summary>
public class Rectangle
{   
}
----

Doctags are well formatted comments that describe the code after it. Each doctag is in XML format and in almost all cases must have a starting element (`<summary>`) and ending element ('</summary>'). Case matters and all doctags are lower case. The text within the tag contains the content that may contain additional, inline, tags.

== Summary

The summary tag always comes first and is applicable to all documentation. It is provides a one sentence summary of the declaration and is generally written as a full sentence.

??

== Inline Tags

see



== See Also

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments[C# Doctags] +