= Constructors
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

A constructor is a special method called when an instance is created.
The purpose of the constructor is to perform any complex initialization for the instance.

When an instance is created using the https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator[new] operator the following, logical, steps occur.

. Memory is allocated in heap for the instance with enough space for all fields in the class.
. Fields are zero initialized.
. Field initializes are executed.
. The constructor specified in `new` is executed.
. The instance is returned as the value of the expression.

This is the only time a constructor can be called and it is called implicitly by the runtime.
It is not possible, in C#, to call a constructor directly.

== Declaring a Constructor

The syntax of a constructor looks like a method except there is no return type and the method name is the type name.

.Constructor Declaration Syntax
----
constructor-declaration ::= [access] T ( [parameter-list] ) { S* }
----

The return type is not needed becuase a constructor called be called directly.

.Constructor Example
[source,csharp]
----
public class Rectangle
{
   //Not necessary to have a constructor here, just for demonstration
   public Rectangle () 
   {     
      Origin = new Point();
   }

   public Point Origin { get; }
   public int Width { get; }
   public int Length { get; }
}
----

NOTE: Unlike other languages do not define a constructor unless the initialization that is needed cannot be done using other, simpler, techniques.

Constructors are designed to do initialization that cannot be done easily using field initializers and to provide a way to quickly initialize an object.
In general constructors should not do anything that calling code could not do itself, such as setting properties.

To call a constructor use it with the `new` operator

.Calling a Constructor
[source,sharp]
----
Rectangle rect = new Rectangle();
----

== Overloading Constructors

Every type has a default constructor that is generated by the compiler.
The default constructor takes no parameters and simply initializes the instance.
There are times when it might be necessary to accept different sets of parameters.
Constructors can be overloaded just like regular methods.

.Constructor Overloading Declaration
[source,csharp]
----
public class Rectangle
{
   //Not necessary to have a constructor here, just for demonstration
   public Rectangle () 
   {     
      Origin = new Point();
      Length = Width = 1;
   }

   public Rectangle ( Point origin, int length, int width )
   {
      Origin = origin;
      Length = length;
      Width = width;
   }

   public Point Origin { get; }
   public int Width { get; }
   public int Length { get; }
}
----

The compiler generates a default constructor for any declared types.
However if the type defines any custom constructors then the default constructor is not generated anymore.
Types that declare any constructors must declare a default constructor if one is needed.

When creating an instance the caller determines the overload to call based upon the arguments being specified.

.Calling an Overloaded Constructor
[source,sharp]
----
Rectangle simpleRect = new Rectangle();
Rectangle complexRect = new Rectangle(center, 10, 10);
----

== Constructor Chaining

One issue with constructor overloading is that often each constructor does the same basic initialization and then some customizations.
In other languages some sort of `Initialize` method is generally created.
The problem with this approach is that the method can be called accidentally by code.
To avoid this issue constructors can chained meaning one constructor can call another.

To chain constructor calls together, in the constructor declaration specify the other constructor overload to call but use the `this` keyword as the method name.

.Constructor Chaining Example
[source,csharp]
----
public class Rectangle
{
   //Call the constructor accepting the data
   public Rectangle () : this(new Point(), 1, 1)
   {          
   }

   public Rectangle ( Point origin, int length, int width )
   {
      Origin = origin;
      Length = length;
      Width = width;
   }

   public Point Origin { get; }
   public int Width { get; }
   public int Length { get; }
}
----

CAUTION: Be careful that a recursive loop does not exist between constructor calls.

When constructor chaining is being used the chained constructor is called first and then the declaring constructor is executed.

== Naming

Constructors must always follow the name of the type and therefore there are no naming guidelines.

== Accessibility

Constructors can be any accessibility with public, protected and private being the most common.

Public constructors allow other code to create an instance of the type.
If a type does not have any public constructors then it cannot be created.

Private constructors are useful for providing special instances of a class.
They can also be used to prevent the construction of a type.

.Private Constructor Example
[source,csharp]
----
public class Rectangle
{
   //Cannot create default instance, but the type can
   private Rectangle () 
   {     
      Origin = new Point();
      Length = Width = 1;
   }

   public Rectangle ( Point origin, int length, int width )
   {
      Origin = origin;
      Length = length;
      Width = width;
   }

   public Rectangle Empty { get; } = new Rectangle();

   public Point Origin { get; }
   public int Width { get; }
   public int Length { get; }
}
----

Protected constructors are useful for allowing derived types to create the class but no one else.

== Documentation

Constructors follow the same documentation rules as methods.

== See Also

link:members.adoc[Class Members] +
link:accessibiilty.adoc[Accessibility] +
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator[C# New Operator] +
