= Navigating the IDE
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

Visual Studio has a lot of user interface elements. It is important to understand some basic terminology.

Dialogs::
Windows that appear in response to certain events. These windows generally alert you to some immediate action and must be closed before you may continue.
Editor Window::
The tabbed window in the middle of the main window. All open files are represented here. This is also the window where editing files will occur.
Menu::
The menu at the top of the screen providing access to the core functionality.
Notifications::
The area in the bottom right of the menu bar where notifications will appear related to updates.
Status Bar::
The area at the bottom of the window with information such as commands being executed and line and column information.
Tool Windows::
The various windows along the top, sides and bottom of the main window. They provide access to functionality outside the main editor window.
Toolbar::
The bars across the top of the main window that provide quick access to common commands.

The IDE is highly customizable. You can adjust the IDE to fit your particular coding style. Some examples of what you can do.

* Toolbars
** Rearrange, show and hide each toolbar.
** Create new toolbars and customize the buttons available on them.
* Tool Windows
** Show or hide tool windows.
** Dock to any side of the main window.
** Detach and float anywhere on the screen.
** Auto-hide (unpin) so the window appears only when it has focus.
** Combine tool windows into tabbed windows to allow grouping.
* Editor Window
** Control order of tabs.
** Pin tabs so they are separate from non-pinned tabs.
** Detach and float the tab (or set of tabs) in their own window.

The IDE supports two different visual layouts: design and debug. 
In design mode the layout of the windows, available toolbars and other features of the UI are optimized for writing code. 
When debugging your code the layout changes to provide access to UI elements that are relevant for debugging. 
In many cases you can adjust the layout to fit your needs for debugging. 
When debugging stops VS will switch back to the design layout.

== General Windows

=== Editor Window

The editor (or document) window is where you will be writing code. 
The editor window consists of one or more tabs representing the open files.

Refer to the section link:editor-window.adoc[Editor Window] for more information.

=== Output Window

The `Output` window is where the IDE puts most messages of importance including build messages, debug messages and general errors.
The window separates the messages by category so use the dropdown list in the window to select the category of messages you want to see. 

Perhaps the most useful aspect of this window is during builds when errors occur. 
Each error will generate a well-defined error message. 
The error message can be double clicked to jump to the appropriate location in your source code.
More importantly, errors are shown in the order they are generated so focus on resolving the errors appearing earlier in the window to avoid wasting time on later errors that are caused by earlier ones.

=== Solution Explorer

The `Solution Explorer` window provides a hierarchial view of the solution and all open projects contained in it. If this window is empty then no solution is open.
Refer to the section on link:solutions.adoc[solutions] for more information about solutions.

Refer to the section link:solution-explorer.adoc[Solution Explorer] for more information about `Solution Explorer`.

== Design Windows

These windows are only useful during design but may be open during link:debugging.adoc[debugging].

=== Error List Window

The `Error List` window will normally appear when you start a build. It contains the list of warnings and errors related to the build. It is dynamically populated as you open windows and perform builds. 

If you double click a line in this window it will jump to the error in the appropriate tab.

WARNING: The errors shown in this window are not ordered. Be careful about fixing errors from this window as they may have been caused by a previous error.

=== Task List Window

The `Task List` window contains a list of tasks that you need to completed based upon the currently open documents. 
This includes certain tasks defined in your source code (using specially formatted comments) but can also include errors from compilation.
You can add tasks to this list to help remind yourself of things to do by using well-formed comments in code. 
```csharp
//TODO: Fix this code
IsBroken();

//HACK: This is a bad way to dit
int x = 4 + 6;
```

== Debug Windows

These windows are only available during link:debugging.adoc[debugging]. Most of the windows only show information while paused in the debugger.

=== Autos Window

The `Autos` window will show you the relevant variables in your code based upon what is currently being executed. 
This will generally include the variables being used before and after the current instruction. 

Information displayed includes the identifier, type and current value. 
Values in red indicate the value has been changed since the window was last refreshed. 
In most cases you can double click the value and change it (within normal semantic rules). This is most useful if you want to alter or test a different value then what the variable currently has.

=== This Window

The `This` window is identical to the `Autos` window except the scope.
It shows only the current instance's (if any) fields and local variables.

== Watch Window

The `Watch` window (of which there are several) is identical to the `Autos` window except for scope.
You can add any expression to this window by right clicking the expression (or value) and selecting `Add to Watch`. 

NOTE: Expressions are not removed from this window but can only be viewed if they are in scope.
