= Getting Started with Visual Studio
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

Visual Studio (VS) is the most advanced integrated development environment (IDE) available today. It is primarily used for
Windows development but it also supports development of iOS, Linux and Android apps. It can be overwhelming to new users. 
This document provides some general help for getting around in Visual Studio, working with code and using the debugger. 
It is based upon Visual Studio 2017 but the suggestions should be useful in other versions.

NOTE: A related product is Visual Studio Code. This newer iteration of Visual Studio is designed for cross-platform development. 
While the products have similar names, they are completely different.

link:ide.adoc[Navigating the IDE] +
link:creating-solution.adoc[Creating a Solution] +
link:solutions.adoc[Solutions and Projects] +
link:builds.adoc[Building Projects] +
link:debugg.adoc[Debugging Basics]

== See Also

link:../readme.adoc[Getting Started] +
link:/setup/readme.adoc[Setting Up]