= Solution Explorer
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

`Solution Explorer` is the core window for viewing and managing projects and your solution. When you are in `Solution Explorer` you should notice a top level node that simply contains a name. This is the solution. Any functionality exposed here impacts all the projects. 
The IDE limits you to one open solution at a time.

Under the solution is a node for each project. The project name should match what you enter when you created it. Any functionality performed on the project node only impacts that node.

`Solution Explorer` is a virtual view of the file system.
A solution is the root directory where your solution file resides.
You can get to this folder quickly by right clicking the solution node and selecting Open Folder in File Explorer.
Each project has its own subfolder under the solution. You can quickly get to that folder by using the same command but on the project node.

== Startup Project

Because a solution may have any number of projects they are all considered equal.
In the case of debugging, it is necessary to identify the project that should be started. This is known as the startup project. The startup project is highlighted in bold in `Solution Explorer`.

Whenever you start the debugger it needs to know which project(s) to run. The debugger can only run executable projects (e.g. console applications).
By default it will run the startup project. However any class libraries are automatically including in the debugging.
The startup project is generally the last project added to the solution that is executable.
To change the startup project (you cannot be debugging at the time) then right click the appropriate project and select `Set as Startup Project`.

NOTE: In advanced situations you can debug multiple executables at the same time by using the `Set Startup Project` command on the solution node and then selecting multiple projects. Remember that only executable projects can be marked as startup projects.

== Working with Files

Projects are made up of files but not every file you open in VS may be part of a project. Unfortunately there is no way to tell if an open file is part of the project or not.
Changing a file that is not part of a project will have no impact on the project itself.

To help avoid issues with files the following is strongly recommended.

. Never open a file or project directly, always either double click the .SLN file in the file system or open Visual Studio and use the Start page to open the recent solution.
. Do not work with the files or projects directly inside the file system. Always use Solution Explorer to open, edit, and rename them.
. To open a file in a project double click it in Solution Explorer.
. If you are unsure whether an open file is in the project then double click the file in Solution Explorer. If it is the correct file then you will return to the same editor window. If it is not then a new window will open.

== Repositories

When working with a Git repository like Github it can be difficult to tell if `Solution Explorer` is connected to the repository or not. This information is available from `Team Explorer` but you can also determine it from the status bar. 

On the right side of the status bar should be the name of the repository that `Solution Explorer` is connected to. If there is nothing there then no repository is open. Furthermore the active branch is shown next to it (e.g. `master`). 

== File View

There is an alternative view in `Solution Explorer` called `Folder View`. 
In this mode `Solution Explorer` is showing the underlying file system layout instead of the solution. 
The layout is determined by the currently active repository.
When in this mode the window title will contain `Folder View`.

WARNING: When in this mode no solution is open and no solution level actions like builds can occur. You can still navigate and edit code but compilation is not available.


