# Datasets
ITSE 1430
Work in Progress
:toc:

The https://docs.microsoft.com/en-us/dotnet/api/system.data.dataset[Dataset] is an in-memory representation of a database. Since it is unrealistic to store the entire database in memory the dataset only contains the set of tables, columns and rows needed for the request. Specifically the dataset is populated with the table(s), columns and rows from the query that is used to populate it.

## Populating a Dataset

## Data Adapters

## Enumerating the Data

## Making Changes to the Data

## Creating an In Memory Database

## Advantages and Disadvantages of Datasets

Datasets have some pros and cons that you should consider before using them.

You may want to use a dataset if any of the following apply.

- The data needs to be modified and pushed back to the database.
- You need to load and work with table relationships.
- You do not have a .NET type that represents the data being returned by the query.
- The amount of data being returned is small (e.g. less than a couple hundred rows).
- You are on an unstable network (e.g. mobile applications) and need a disconnected copy of the data.
- The structure of the data is not known in advance (e.g. dynamic queries).

You should consider using a data reader or other approach if any of the following apply.

- Performance is critical. Datasets use data readers under the hood to read data and must build the table structure which is slow.
- Memory constraints are tight. Datasets keep a copy of the schema plus at least one copy of each row. 
- The amount of data is large (e.g. more than a couple hundred of rows). The overhead of a dataset gets worse as the number of rows increase.
- You are going to convert the rows of data to a business object.
- You need read only access to the data.

## See Also

link:datareader.adoc[Data Readers]