= Ordinals vs Strings
ITSE 1430 
:toc:

When reading data it is necessary to map from the database identifier to the client side data model. For ADO.NET this means using eithe a zero-based ordinal or a string name.

## Ordinal

An ordinal is simply a zero-based offset of the column. The first column is ordinal 0, the second column ordinal 1, etc. 

Ordinals closely mimic the index of an array and tend to map one-to-one to the underlying data. As a result ordinals tend to be very fast for accessing data. If performance is an issue then ordinals are the clear winner.

The downside to ordinals is that ordering of columns is important. If a query can return data back in arbitrary column order then an ordinal cannot be used. There would be no way to tell, for example, between a name and description column based upon ordinal alone. Generally this is not an issue because queries should always be explicit about the columns they are returning. The ordering of the column cannot change without breaking existing code.

## Column Name

A column name is simply the name of the column that was in the query. Most columns in a query have a name but some might not, for example calculated column values. Column names are rarely case sensitive. 

Column names are generally easier to read. `GetString("Name")` makes more sense than `GetString(0)`. Furthermore the issue of column ordering goes away when using column names. The query can return columns back in any order and the name will always work.

In order to use a column name it is necessary to map the column name to the index in the array of values being returned. In some cases this is handled by the infrastructure, for example `DataRow`. But in other cases this must be handled in the code explicitly. It is inefficient to keep looking up a column's index for each row as it wouldn't change for the life of the current query. Therefore caching is needed.

Another issue with column names is that they must match what the query returns. Often a query returns the underlying column name from the table. If a column name changes then any query using it will also change. This will break code that relies on the name. To work around this impacted queries would need to use an alias to keep the original column name.