= Label Control
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.label[Label] control displays a fixed set of text in a form.
The text is not interactive and does not get keyboard input.

Use the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.linklabel[LinkLabel] if you want a link that can be clicked.

== Setting Up the Control

The only property that needs to be set on the control is https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.buttonbase.text[Text].

.Label Setup Example
[source,csharp]
----
void Configure ()
{
   Label nameLabel = new Label();
   nameLabel.Text = "Name";
}
----

NOTE: Normally setup is done through the designer.

== Accelerators

Sometimes it is useful to jump to a label using the keyboard.
This is known as an accelerator and allows a user to quickly get to a location in the form.
To use an accelerator set the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.buttonbase.text[Text] property with text that has an ampersand (`&`) in it.
The character immediately following the ampersand is the accelerator.
If the user presses the accelerator key then the focus will
jump to that control.

== See Also

link:readme.adoc[Windows Forms] +
link:controls.adoc[Controls] +
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.label[Label Class] +
