= ComboBox Control
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox[ComboBox] control is used to show a list of values to the user. 
The control also shows a textbox that allows the user to free type.
The user can select a single value from the list or, by default, enter a new value.

== Setting Up the Control

To use a combobox place it onto the form.

The following properties are most commonly set as part of the control.

.Common Button Properties
|===
| Property | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource] | Used for data binding (see below).
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.displaymember[DisplayMember] | Used for data binding (see below).
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.dropdownstyle[DropDownStyle] | Determines how the list is rendered (see below).
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] | Used for data binding (see below).
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedindex[SelectedIndex] | Gets the index of the selected item (see below).
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selecteditem[SelectedItem] | Gets the selected item (see below).
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedtext[SelectedText] | Gets the text of the selected item (see below).
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedvalue[SelectedValue] | Gets the value of the selected item (see below).
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.valuemember[ValueMember] | Used for data binding (see below).
|===

.ComboBox Setup Example
[source,csharp]
----
void Configure ()
{
   ComboBox cbOptions = new ComboBox();
   cbOptions.Items.Add("First");
   cbOptions.Items.Add("Second");
}
----

NOTE: Normally setup is done through the designer.

Unlike the other controls the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.text[Text] property is not used for this control.
Instead items must be added to the control so they can be selected.

=== Fixed vs Freeform List

By default the control provides a list of items to be selected by the user but the user can type in their own value instead.
This is known as a freeform list.
The primary use of this is to provide the user will a preset list of options but allow them to use something else.

If the list represents a fixed list of items and the user should not be allowed to select anything else then change the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.dropdownstyle[DropDownStyle] property to https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.comboboxstyle[ComboBoxStyle.DropDownList].

.ComboBox Fixed List
[source,csharp]
----
//Make fixed list
cbOptions.DropDownStyle = ComboBoxStyle.DropDownList;
----

== Data Binding

To use the control items must be added to its list, generally known as data binding.
The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] property is a collection of objects. 
Any object can be added to the collection although normally a single type is used.
The control calls the https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring[ToString] method on the object, by default, to get the textual representation.

Data binding can be done either declaratively, through the designer, or programmatically in code depending upon need.
Additionally the control supports data binding using either simple or complex binding.

=== Declarative Data Binding

Declarative binding is the easiest and is done using the designer. 
Use either the smart tag on the control or edit the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] property to bring up the `Items Editor`.
In the editor enter the list of strings to show in the control, each on their own line.

The designer will add each string to the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] property.

In many cases the bound data is instances of complex types. 
In this case the designer is not going to work.
Instead the data needs to be bound programmatically and to do that there are two different ways depending upon the data being bound.

=== Binding Using Items

The first approach is to continue to use the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] property.
This is the simplest approach but limited.
Since https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] is a collection of objects any data can be added to it.
In order to display the data properly ensure the https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring[ToString] method on the instance returns a user-friendly string.

.Data Binding with Items
[source,csharp]
----
//Assume a class called Employee with a Name property and ToString returns the Name

//Option 1: Add one at a time if a transformation is needed
foreach (var employee in employees)
   cbEmployees.Items.Add(employee);

//Option 2: Add them all at once
cbEmployees.Items.AddRange(employees);
----

CAUTION: Ensure the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] property is empty before adding items otherwise the items will be duplicated.

=== Binding Using a Data Source

The second approach to data binding is to use the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource] property.
This is the most advanced approach with some limitations but provides the best flexibility.

CAUTION: If both https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource] and https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] is set then https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource] will override whatever is in https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items].

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource] property requires an array or list of objects.
At runtime if the object being assigned to the property does not implement the appropriate interfaces then a runtime error occurs.

.Data Binding with DataSource
[source,csharp]
----
cbEmployees.DataSource = employees;
cbEmployees.DisplayMember = nameof(Employee.Name);
cbEmployees.ValueMember = nameof(Employee.Id);
----

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource] property provides the values to choose from but since a complex object is often used the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.displaymember[DisplayMember] and https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.valuemember[ValueMember] properties are also generally set.

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.displaymember[DisplayMember] property specifies the name of the property that is used to show the textual value in the list. In the above example it would be the `Name` property. This eliminates the need for a custom https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring[ToString] method.

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.valuemember[ValueMember] property specifies the name of the property that is used for the value of the item. This is useful if you want to use a value different than the instance itself. In the above example the `Id` property is the value of the list item.

NOTE: Normally a https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.bindingsource[BindingSource] is used instead of an array or list directly. This has many benefits but is beyond the scope of this course.

== Getting or Setting the Selected Item

Once data is bound to the control then code can get or set the currently selected item, if any, from the list.
How this is done depends upon how the data is bound.

=== SelectedIndex Property

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedindex[SelectedIndex] property specifies the zero-based index of the selected item, if any.
It works in all cases but when using https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource] it may not be possible to map the index back to a value.

.Using SelectedIndex
[source,csharp]
----
Employee GetSelectedItem ()
{
   var index = cbEmployees.SelectedIndex;
   if (index < 0)
      return null;

   //Not safe...
   var employees = cbEmployees.DataSource as Employee[];

   return employees != null ? employess[index] : null;
}
----

=== SelectedItem Property

If the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.items[Items] property was used to bind the data then the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selecteditem[SelectedItem] property can be used to retrieve or set it.

.Using SelectedItem
[source,csharp]
----
Employee GetSelectedItem ()
{
   return cbEmployees.SelectedItem as Employee;
}
----

NOTE: When setting the property it is set by finding the corresponding item in the control using the equality rules of the type.

=== SelectedText Property

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedtext[SelectedText] property gets the text of the selected item. 
The text will match the result of calling the https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring[ToString] method on the currently selected item, if any.
When using the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource] property then it will match the property defined by https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.displaymember[DisplayMember].

.Using SelectedText
[source,csharp]
----
Employee GetSelectedItem ()
{
   var text = cbEmployees.SelectedText;
   if (!String.IsNullOrEmpty(text))
      return FindEmployee(cbEmployees, text);

   return null;
}
----

=== SelectedValue Property

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedvalue[SelectedValue] property is only useful when using https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.datasource[DataSource]. 
The value matches the property of the selected item as defined by https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.valuemember[ValueMember]

.Using SelectedValue
[source,csharp]
----
Employee GetSelectedItem ()
{
   var value = cbEmployees.SelectedValue;
   if (value != null &&)
   {
      var id = (int)value;

      return FindEmployee(cbEmployees, id);
   };

   return null;
}
----

== Responding to Selection Changes

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedindexchanged[SelectedIndexChanged] event notifies code when the selected item has changed.
It is raised whether the data is changed programmatically or by the user.

.ComboBox SelectedIndexChanged Example
[source,csharp]
----
//cbOptions.SelectedIndexChanged += OnEmployeeSelected;
void OnEmployeeSelected ( object sender, EventArgs e )
{   
   var employee = GetSelectedEmployee();
   if (employee != null)
      EnableOptions();
}
----

== See Also

link:readme.adoc[Windows Forms] +
link:controls.adoc[Controls] +
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.bindingsource[BindingSource] +
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox[ComboBox Class] +
link:controls-listbox.adoc[ListBox Control] +