= CheckBox Control
Michael Taylor <michael.taylor@tccd.edu>
v1.0
:toc:

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox[CheckBox] control provides a two or three-way toggle to the user.
It is most often used to allow the user to choose a true/false option but it does support an intermediate state for advanced situations.

== Setting Up the Control

To use a checkbox place it onto the form.

The following properties are most commonly set as part of the control.

.Common Button Properties
|===
| Property | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checked[Checked] | Determines if the control is checked or not.
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checkstate[CheckState] | Determines the state of the checkbox.
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.buttonbase.text[Text] | Sets the text on the control.
|===

.CheckBox Setup Example
[source,csharp]
----
void Configure ()
{
   CheckBox chkIsOnSale = new CheckBox();
   chkIsOnSale.Text = "On Sale?";   
}
----

NOTE: Normally setup is done through the designer.

== Using the Control

To get the status of the checkbox get the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checked[Checked] property.
To set the status of the checkbox set the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checked[Checked] property.

NOTE: By default the control reacts to click requests automatically so there is no need to programmatically toggle the check state.

If the UI needs to update in response to a change in the check state of the control then handle the
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checkedchanged[CheckChanged] event.

.Check Changed Example
[source,csharp]
----
//chkIsOnSale.CheckedChanged = OnSalesCheckedChanged;
void OnSalesCheckedChanged ( object sender, EventArgs e )
{   
   if (chkIsOnSale.Checked)
      EnableSalesControls();
   else
      DisableSalesControls();
}
----

== Tri-State Control

If the control needs to support three states then the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checked[Checked] property will no longer work because it is a boolean value.
Use the https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checkstate[CheckState] proeprty. 
It works the same way but is an enumerated value.

If it is necessary to handle change events then use the 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checkstatechanged[CheckStateChanged] event instead of https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox.checkedchanged[CheckedChanged].

.Tri-State Example
[source,csharp]
----
//Initialization
CheckBox chkYesNoMaybe = new CheckBox();
chkYesNoMaybe.Text = "Yes/No/Maybe";

//Handler
//chkYesNoMaybe.CheckStateChanged = OnYesNoMaybeChanged;
void OnYesNoMaybeChanged ( object sender, EventArgs e )
{
   switch (chkYesNoMaybe.CheckState)
   {
      case CheckState.Checked:      //Yes
      case CheckState.Unchecked:    //No
      case CheckState.Indeterminate://Maybe
   };
}
----

== See Also

link:readme.adoc[Windows Forms] +
link:controls.adoc[Controls] +
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkbox[CheckBox Class] +
link:controls-radiobutton.adoc[RadionButton] +
