= ComboBox Control
Michael Taylor <michael.taylor@tccd.edu>
v0.1
:toc:

The https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox[ComboBox] control is used to show a list of values to the user.
The list may be fixed or freeform.

??
== Setting Up the Control

To use a button place it onto the form.

The following properties are most commonly set as part of the control.

.Common Button Properties
|===
| Property | Purpose
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.button.dialogresult[DialogResult] | Sets the result to use when the button is clicked and the parent form is closed.
| https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.buttonbase.text[Text] | Sets the text on the button.
|===

.Button Setup Example
[source,csharp]
----
void Configure ()
{
   Button saveButton = new SaveButton();
   saveButton.Text = "Save";
   saveButton.DialogResult = DialogResult.OK;
}
----

NOTE: Normally setup is done through the designer.

== Using the Control

To use the control handle the https://docs.microsoft.com/en-us/dotnet/api/system.windows.control.click[Click] event.

.Button Click Example
[source,csharp]
----
//btnSave.Clicked += OnSave;
void OnSave ( object sender, EventArgs e )
{   
   if (DataIsValid())
   {
      DialogResult = btnSave.DialogResult;
      Close();
   };

   //Ignore the click
   DialogResult = DialogResult.None;
}
----

CAUTION: If the clicked button's `DialogResult` is set then the `Click` event automatically sets the form's `DialogResult` to the button's value. When the event handlers finish executing then if the form's `DialogResult` property is set then the form automatically closes.

== Fixed vs Freeform List

???

== See Also

link:readme.adoc[Windows Forms] +
link:controls.adoc[Controls] +
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox[ComboBox Class] +
link:controls-listbox.adoc[ListBox Control] +