= Commands
ITSE 1430
:toc:

To do any work in a database a command must be sent. Each command is a request to the database to do some work. As with connections each provider has its own command type. 

A https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand[command] consists of the command text to execute and the connection it is associated with. Without a connection the command has no context. Commands have some additional options to control their behavior.

.Common Command Properties
|===
| Property | Description 
| https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtext[CommandText] | The command to execute.
| https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtype[CommandType] | The command type of the command.
| https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.connection[Connection] | The connection to run the command under.
| https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.parameters[Parameters] | The parameters associated with the command.
|===

Commands do implement `IDisposable` but generally do nothing so code can clean up a command when done. Wrapping a command with a `using` statement is generally appropriate.

Commands can be reused (provided they are not disposed). It is common to execute a command, change the command text and run it again. This reduces the number of objects being created.

CAUTION: Command behavior can vary wildly between providers. Ensure that commands are tested against the actual provider that will be used.

## Creating a Command

Creating a command can be done in several different ways. The common approach is to create the object directly. 

.Creating a Command with New
[source,csharp]
----
var cmd = new SqlCommand("SELECT ...", conn);
----

The alternative approach is to create it through the connection's https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.createcommand[CreateCommand] method.

.Creating a Command with CreateCommand
[source,csharp]
----
var cmd = conn.CreateCommand();
cmd.CommandText = "SELECT ...";
----

If the command is not an "ad hoc" SQL command (e.g. `SELECT` or `INSERT`) then set the https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtype[CommandType] as well. For example a SQL stored procedure has to set the `CommandType`.

.Calling a SQL Stored Procedure
[source,csharp]
----
var cmd = new SqlCommand("GetProducts", conn);
cmd.CommandType = CommandType.StoredProcedure;
----

CAUTION: Failure to set `CommandType` properly will result in a runtime error.

## Creating Parameterized Commands

Often a command requires parameters. Parameterized queries can be used anywhere including in adhoc queries. Adding parameters to a command requires adding them to the https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.parameters[Parameters] property. This can be done in several different ways.

For SQL server (and some other providers) with an input parameter use the https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlparametercollection.addwithvalue[AddWithValue] method.

.Adding a Parameter with AddWithValue
[source,csharp]
----
var cmd = new SqlCommand("AddProduct", conn);
cmd.CommandType = CommandType.StoredProcedure;

cmd.Parameters.AddWithValue("@name", name);
----

NOTE: SQL server requires an @ (at) sign in front of each parameter. It is a database configuration option whether case matters but most SQL databases are case insensitive.

When using other database providers the more generic https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlparametercollection.add[Add] method can be used. It has several overloads.

.Adding a Parameter with Add
[source,csharp]
----
var cmd = new SqlCommand("AddProduct", conn);
cmd.CommandType = CommandType.StoredProcedure;

var parmDescription = cmd.Parameters.Add("@description", SqlDbType.NVarChar);
parmDescription.Value = description;
----

For more complex parameters, such as output parameters, create the parameter directly.

.Creating and Adding a Parameter
[source,csharp]
----
var cmd = new SqlCommand("AddProduct", conn);
cmd.CommandType = CommandType.StoredProcedure;

var parmId = new SqlParameter("@id", 0);
parmId.Direction = ParameterDirection.Output;
cmd.Parameters.Add(parmId);
----

Like `SqlConnection` the parameter can be created directly off the `SqlCommand` using the https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.createparameter[CreateParameter] method.

.Creating and Adding a Parameter
[source,csharp]
----
var cmd = new SqlCommand("AddProduct", conn);
cmd.CommandType = CommandType.StoredProcedure;

var parmRating = cmd.CreateParameter();
parmRating.ParameterName = "@rating";
cmd.Parameters.Add(parmRating);
----

WARNING: Always use parameterized queries when accepting user input. https://owasp.org/www-community/attacks/SQL_Injection[SQL injection] attacks are in the top 10 list of security vulnerabilities that are commonly exploited. By using an unparameterized query a hacker can potential execute any SQL command inside a database irrelevant of the orignal SQL command. Using parameterized queries prevents this and often makes the query easier to read.

## Executing Commands

Executing a command runs it on the database server. A database command always returns a result but what that result means is dependent upon the command. Therefore there are different methods on the command to control how the return value is interpreted.

### Command With No Return Value

Commands that just modify data like `DELETE` and `UPDATE` either return no data or return the number of rows impacted. In these cases the return value is typically ignored. To execute a command and ignore the result use the https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.executenonquery[ExecuteNonQuery] method.

.Executing a Command with No Return Value
[source,csharp]
----
cmdDelete.ExecuteNonQuery();
----

### Command With a Single Return Value

Commands like `INSERT` generally return back a key representing the newly inserted row. Other commands may also return a single value with a count or some other value. For commands that return a single value, or in which only the first value is relevant the https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.executescalar[ExecuteScalar] method can be used. This method returns the first value of the first row, if any. 

.Executing a Command with a Single Return Value
[source,csharp]
----
var result = cmdInsert.ExecuteScalar();
var id = Convert.ToInt32(result);
----

The value is treated as an `object` so typecasting must be done to convert it to the correct type.

### Command With Query Results

Query commands can return a large number of rows with multiple data points in each row. The traditional methods do not work with them. Refer to the sections link:dataset[Dataset] and link:datareader[Data Reader] for information on how to read data.

## See Also

link:connections.adoc[Connections] +
link:providers.adoc[Database Providers] +
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand[SqlCommand]
